version: "3.8"

services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql